name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production-ready build files
        uses: actions/download-artifact@v3
        with:
          name: react-app

      - name: Deploy
        run: |
          # Deployment script or commands here
